server:
  port: 7901
 
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: microservice-provider-user-eureka
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
   
eureka:
  client:
    service-url: 
      defaultZone: http://user:password@localhost:8741/eureka
      #defaultZone: http://user:password@peer1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  