spring:
  application:
    name: microservice-gateway-zuul-reg-expression
server:
  port: 8740
  
eureka:
  client:
    service-url: 
      defaultZone: http://user:password@localhost:8741/eureka
  instance:
    prefer-ip-address: true
    