server:
  port: 7906
  
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-factory
   
eureka:
  client:
    service-url: 
      defaultZone: http://user:password@localhost:8741/eureka
  instance:
    prefer-ip-address: true
  
  