server:
  port: 8010
  
spring:
  application:
    name: microservice-consumer-movie-ribbon
   
eureka:
  client:
    service-url: 
      defaultZone: http://user:password@localhost:8741/eureka
  instance:
    prefer-ip-address: true

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule